version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: recipe-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-recipe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-recipe_password}
      POSTGRES_DB: ${POSTGRES_DB:-recipe_app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recipe_network

volumes:
  postgres_data:


networks:
  recipe_network:
