version: '3.8'
services:
  backend:
    build: ./backend
    container_name: recipe-backend
    ports:
      - "8000:8000" # Beispielport für FastAPI
    volumes:
      - ./backend:/app
    networks:
      - recipe_network

networks:
  recipe_network:
